### ISSUE TITLE
Invalid application id

### ISSUE THREAD

**Issue by ratracegrad** [samuelcouch/node-teespring#2]
Just installed your repo and when I run it I get this result:
{
  "message": "Invalid Application-ID or API key",
  "status": 403
}

**Comment by samuelcouch** [comment]
This is likely related to Teespring updating their API keys. I'm away from a computer for the next week, but the file in question is https://github.com/samuelcouch/node-teespring/blob/master/lib/conf.js 

In order to get the updated details, you will have to go to Teespring and inspect the page requests when you search.

**Comment by samuelcouch** [comment]
I just had a chance to look in to this, nothing seems to have changed with teespring, and it works on my end. I did push an update to use Algolia's `https` endpoint instead of `http`, but I think it's unlikely that's what was causing your error. 

How are you implementing it into your codebase?
